name: flutter_build_mode
description: Get 3 build modes of your Flutter app, release, profile, and debug!
version: 1.1.0
homepage: https://github.com/okaryo/flutter_build_mode
repository: https://github.com/okaryo/flutter_build_mode

environment:
  sdk: ">=2.12.0  <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
