name: flutter_build_mode
description: Get the build mode of your Flutter app!
version: 1.0.0
homepage: https://github.com/okaryo/flutter_build_mode
repository: https://github.com/okaryo/flutter_build_mode

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
