name: flutter_build_mode
description: A package that extends the use of the 3 build modes, release, profile, and debug, for Flutter apps!
version: 1.1.1
homepage: https://github.com/okaryo/flutter_build_mode
repository: https://github.com/okaryo/flutter_build_mode

environment:
  sdk: ">=2.12.0  <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
